"use client";

import { useState, useCallback } from "react";
import { useReducedMotion } from "motion/react";
import {
  Sparkles,
  Copy,
  Check,
  Loader2,
  PenTool,
  Layers,
  Type,
  Star,
} from "lucide-react";

interface LogoInteractiveDemoProps {
  className?: string;
}

type LogoStyleOption =
  | "minimalist"
  | "modern"
  | "corporate"
  | "creative"
  | "luxury"
  | "tech";

const STYLE_PROMPTS = {
  minimalist: {
    mj:
      "minimalist logo design, clean lines, geometric shapes, modern typography, professional aesthetic, scalable vector style --v 6 --ar 1:1 --stylize 100 --no shading",
    vector:
      "Minimalista vektoros logo - tiszta vonalvezetés, geometriai forma, egyetlen szín, skálázható SVG kulisszával. Monogram vagy ikon alapú, háttér nélkül, stroke-only stílus.",
    description: "Tiszta, egyszerű vonalvezetés",
  },
  modern: {
    mj:
      "modern logo design, contemporary aesthetic, bold typography, dynamic shapes, innovative visual identity --v 6 --ar 1:1 --stylize 250 --no gradient",
    vector:
      "Modern, kortárs vektoros logo - erős betűtípus, dinamikus formák, kontrasztos színvilág. Flat design, minimális gradient, modern és innovatív megjelenés.",
    description: "Kortárs, innovatív",
  },
  corporate: {
    mj:
      "corporate logo design, professional business aesthetic, trustworthy colors, clean typography, established brand feel --v 6 --ar 1:1 --stylize 150 --no cartoon",
    vector:
      "Professzionális üzleti logo - megbízható színvilág (kék, szürke, fekete), tiszta tipográfia, established brand élmény. Alázatos, tömör és emlékezetes.",
    description: "Professzionális, üzleti",
  },
  creative: {
    mj:
      "creative logo design, vibrant colors, artistic elements, unique composition, eye-catching visual --v 6 --ar 1:1 --stylize 400 --no watermark",
    vector:
      "Kreatív, vibráns vektoros logo - élénk színvilág, művészi elemek, egyedi kompozíció. Kidolgozott részletek, színes rétegek, eye-catching vizualitás.",
    description: "Színes, dinamikus",
  },
  luxury: {
    mj:
      "luxury logo design, elegant script typography, gold accents, sophisticated composition, high-end brand identity --v 6 --ar 1:1 --stylize 300 --no flat design",
    vector:
      "Luxus, elegáns logo - drága arany akcentusok, grafit díszítések, kizárólag bezier görbék, premium vektor. Kiváló minőségű, print-ready készítésű brand asset.",
    description: "Prémium, elegáns",
  },
  tech: {
    mj:
      "technology logo design, futuristic shapes, circuit patterns, tech branding, innovation symbol, AI company logo --v 6 --ar 1:1 --stylize 200 --no organic",
    vector:
      "Tech logo - jövőbeli geometricus alakzatok, áramköri minták, AI és innováció szimbólumai. Neon kék és könnyed vonalvezetés, digital-first megjelenés.",
    description: "Technológiai, jövőismerős",
  },
};

const STYLES: LogoStyleOption[] = [
  "minimalist",
  "modern",
  "corporate",
  "creative",
  "luxury",
  "tech",
];

const AI_DESCRIPTION =
  "Generated by the WebDude AI Logo Műhely — A Next.js 16, React 19 és Firebase-alapú intelligens logogenerátor, amely profi, vektoralható logókat és Midjourney/későbbi AI promptokat készít a cégidentitás teljes körű kialakításához.";

const FEATURES_LIST = [
  "Midjourney v6-ready prompt generáció (icon-only és wordmark variánsok)",
  "Vektoros logó szöveges leírása SVG/Stripe kulisszával",
  "AI-alapú stílusajánló: minimalist, modern, corporate, creative, luxury, tech",
  "One-click másolás a generált tartalmakhoz (clipboard API)",
  "WCAG AA kontraszt: arany (#f59e0b) gombok szövege sötét (#020617)",
  "Reduced motion támogatás (useReducedMotion hook)",
];

const CHARS_PER_LINE = 58;

export default function LogoInteractiveDemo({
  className,
}: LogoInteractiveDemoProps) {
  const shouldReduceMotion = useReducedMotion();
  const [selectedStyle, setSelectedStyle] = useState<LogoStyleOption>("minimalist");
  const [copiedKeys, setCopiedKeys] = useState<Record<string, boolean>>({});
  const [copiedAll, setCopiedAll] = useState(false);
  const [hoveredRow, setHoveredRow] = useState<number | null>(null);

  const copyToClipboard = useCallback(async (text: string, key: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedKeys((prev) => ({ ...prev, [key]: true }));
      setTimeout(() => setCopiedKeys((prev) => ({ ...prev, [key]: false })), 1800);
    } catch {}
  }, []);

  const copyAllToClipboard = useCallback(async () => {
    const allText = [
      "=== Logo AI Műhely — Generált Tartalmak ===",
      "",
      `Stílus: ${selectedStyle}`,
      "",
      `Midjourney Prompt (icon-only):`,
      STYLE_PROMPTS[selectedStyle].mj,
      "",
      `Vektoros Leírás (SVG kulisszával):`,
      STYLE_PROMPTS[selectedStyle].vector,
      "",
      `Stílus Leírás:`,
      STYLE_PROMPTS[selectedStyle].description,
    ].join("\n");
    try {
      await navigator.clipboard.writeText(allText);
      setCopiedAll(true);
      setTimeout(() => setCopiedAll(false), 2200);
    } catch {}
  }, [selectedStyle]);

  const stylePrompt = STYLE_PROMPTS[selectedStyle];

  return (
    <div className="bg-[#020617] rounded-2xl border border-[#1e293b] p-6 md:p-8">
      {/* Fejléc */}
      <div className="flex flex-col gap-3 mb-8 border-b border-[#1e293b] pb-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-4">
            <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-[#f59e0b]/10 border border-[#f59e0b]/30">
              <Sparkles className="w-6 h-6 text-[#f59e0b]" />
            </div>
            <div>
              <h2 className="text-xl md:text-2xl font-bold text-[#e2e8f0] tracking-tight">
                Logo AI Műhely
              </h2>
              <p className="text-sm text-[#94a3b8] mt-1">
                AI-alapú logógenerálás és MJ prompt készítés
              </p>
            </div>
          </div>

        {/* Zárás: fejléc és fő konténer */}
        </div>
      </div>
    </div>
  );
}
